### ISSUE TITLE
构建在线文档时报错： cannot import name 'etree' from 'markdown.util' 

### ISSUE THREAD

**Issue by always-james** [metersphere/docs#52]
按照文档构建说明，安装了Python环境，执行了requirements.txt文件安装了所需的依赖，在执行“mkdocs serve”时报错：

ERROR    -  Config value 'markdown_extensions': Failed to load extension 'lightg                                         allery'.
  File "d:\program_base_env\python-3.8\lib\site-packages\lightgallery.py", line                                          3, in <module>
    from markdown.util import etree
ImportError: cannot import name 'etree' from 'markdown.util' (d:\program_base_en                                         v\python-3.8\lib\site-packages\markdown\util.py)

原先的Python版本为3.7，后来网上查找处理方案时有说3.8可以解决此问题，于是更换了Python3.8的版本，但问题依旧。
请百忙中帮忙看一下这个问题。
谢谢。

**Comment by shenkaibo** [comment]
在线文档 对应分支为 v1.20.x-lts 和 v2.x ，请切到这两个分支再起一下
